### ISSUE TITLE
cannot upload data sources

### ISSUE THREAD

**Issue by torrmal** [mindsdb/mindsdb_server#17]
I get this error:

```
Exception on /datasources/yep [PUT]
Traceback (most recent call last):
  File "/Users/jorgetorres/Library/Python/3.7/lib/python/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jorgetorres/Library/Python/3.7/lib/python/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/jorgetorres/Library/Python/3.7/lib/python/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_restplus/marshalling.py", line 136, in wrapper
    resp = f(*args, **kwargs)
  File "/Users/jorgetorres/src/mindsdb/mindsdb_server/mindsdb_server/namespaces/datasource.py", line 101, in put
    names = [x['name'] for x in get_datasources()]
  File "/Users/jorgetorres/src/mindsdb/mindsdb_server/mindsdb_server/namespaces/datasource.py", line 43, in get_datasources
    with open(os.path.join(ROOT_STORAGE_DIR, ds_name, 'metadata.json'), 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'storage/predictors/metadata.json'
```

**Comment by StpMax** [comment]
fixed after 2e77f0e08fadcec5cab920ca403dbc160df9a2ca
