### ISSUE TITLE
download of predictor not working 

### ISSUE THREAD

**Issue by torrmal** [mindsdb/mindsdb_server#24]
On MAC, this is the error:

```

Exported model to nr_rooms.zip 127.0.0.1 - - [04/Jun/2019 11:04:26] "[1m[35mGET /predictors/nr_rooms/download HTTP/1.1[0m" 500 -

Exception on /predictors/nr_rooms/download [GET] Traceback (most recent call last): File "/Users/jorgetorres/Library/Application Support/mindsdb_gui/mindsdb_server/env/lib/python3.7/shutil.py", line 557, in move os.rename(src, real_dst) FileNotFoundError: [Errno 2] No such file or directory: 'nr_rooms.zip' -> 'tmp/nr_rooms.zip' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/Users/jorgetorres/Library/Application Support/mindsdb_gui/mindsdb_server/env/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request rv = self.dispatch_request() File "/Users/jorgetorres/Library/Application Support/mindsdb_gui/mindsdb_server/env/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/Users/jorgetorres/Library/Application Support/mindsdb_gui/mindsdb_server/env/lib/python3.7/site-packages/flask_restplus/api.py", line 325, in wrapper resp = resource(*args, **kwargs) File "/Users/jorgetorres/Library/Application Support/mindsdb_gui/mindsdb_server/env/lib/python3.7/site-packages/flask/views.py", line 88, in view return self.dispatch_request(*args, **kwargs) File "/Users/jorgetorres/Library/Application Support/mindsdb_gui/mindsdb_server/env/lib/python3.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request resp = meth(*args, **kwargs) File "/Users/jorgetorres/Library/Application Support/mindsdb_gui/mindsdb_server/env/lib/python3.7/site-packages/mindsdb_server/namespaces/predictor.py", line 229, in get shutil.move(fname, fpath) File "/Users/jorgetorres/Library/Application Support/mindsdb_gui/mindsdb_server/env/lib/python3.7/shutil.py", line 571, in move copy_function(src, real_dst) File "/Users/jorgetorres/Library/Application Support/mindsdb_gui/mindsdb_server/env/lib/python3.7/shutil.py", line 257, in copy2 copyfile(src, dst, follow_symlinks=follow_symlinks) File "/Users/jorgetorres/Library/Application Support/mindsdb_gui/mindsdb_server/env/lib/python3.7/shutil.py", line 121, in copyfile with open(dst, 'wb') as fdst: FileNotFoundError: [Errno 2] No such file or directory: 'tmp/nr_rooms.zip'

```

it seems like the file is not being generates as tmp/nr_rooms.zip

**Comment by George3d6** [comment]
Should be fixed, please try again.
