### ISSUE TITLE
ImportError: cannot import name 'cached_property' from 'werkzeug'

### ISSUE THREAD

**Issue by ZoranPandovski** [mindsdb/mindsdb_server#51]
Installing the latest minds_server error throws Import error with the latest Flask-restplus version.
Flask-restplus have Werkzeug as a dependency that has some import changes in (1.0.0)latest version. https://github.com/noirbizarre/flask-restplus/issues/777#issuecomment-583390813

```
Time series encoders can't be loaded
Traceback (most recent call last):
  File "server.py", line 1, in <module>
    from mindsdb_server.namespaces.predictor import ns_conf as predictor_ns
  File "/home/zoran/MyProjects/mindsdb_server/ser/lib/python3.7/site-packages/mindsdb_server/__init__.py", line 6, in <module>
    from mindsdb_server.server import start_server
  File "/home/zoran/MyProjects/mindsdb_server/ser/lib/python3.7/site-packages/mindsdb_server/server.py", line 1, in <module>
    from mindsdb_server.namespaces.predictor import ns_conf as predictor_ns
  File "/home/zoran/MyProjects/mindsdb_server/ser/lib/python3.7/site-packages/mindsdb_server/namespaces/predictor.py", line 12, in <module>
    from flask_restplus import Resource, abort
  File "/home/zoran/MyProjects/mindsdb_server/ser/lib/python3.7/site-packages/flask_restplus/__init__.py", line 4, in <module>
    from . import fields, reqparse, apidoc, inputs, cors
  File "/home/zoran/MyProjects/mindsdb_server/ser/lib/python3.7/site-packages/flask_restplus/fields.py", line 17, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property' from 'werkzeug' (/home/zoran/MyProjects/mindsdb_server/ser/lib/python3.7/site-packages/werkzeug/__init__.py)
```

**Comment by George3d6** [comment]
Again, should have been fixed by @ZoranPandovski 's PR, closing

**Comment by Jowjow** [comment]
not fixed

**Comment by ZoranPandovski** [comment]
@Jowjow Can you please share more information? Are you getting this exception when running the server?
